version: '3'
services:

  poll-service-mongodb:
    container_name: poll-service-mongodb
    image: mongo:4.2-bionic
    restart: unless-stopped
    ports:
      - 27017:27017

  poll-service:
    container_name: poll-service
    image: poll-service:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - SPRING_DATA_MONGODB_HOST=poll-service-mongodb
    depends_on:
      - poll-service-mongodb
